import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "@/components/provider";
import { UserProvider } from "@/components/userProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <UserProvider>
            <main className="grid min-h-screen w-screen place-items-center bg-blue-100">
              {children}
            </main>
          </UserProvider>
        </Providers>
      </body>
    </html>
  );
}
